import React from 'react';
import { X, Printer, FileText, Check } from 'lucide-react';
import { fetchOrders } from '../services/supabaseService';

export default function ZReportModal({ isOpen, onClose, settings, session }) {
  const [sales, setSales] = React.useState([]);

  React.useEffect(() => {
    if (!isOpen) return;
    fetchOrders({ limit: 500 }).then(data => setSales(data));
  }, [isOpen]);

  if (!isOpen) return null;

  const today = new Date().toISOString().split('T')[0];
  const todaySales = sales.filter(s => (s.created_at || s.timestamp || '').startsWith(today));

  const regularSales = todaySales.filter(s => s.order_type !== 'refund');
  const refunds = todaySales.filter(s => s.order_type === 'refund');

  const totalRevenue = regularSales.reduce((sum, s) => sum + (s.total || 0), 0);
  const totalSubtotal = regularSales.reduce((sum, s) => sum + (s.subtotal || 0), 0);
  const totalTax = regularSales.reduce((sum, s) => sum + (s.tax_total || 0), 0);
  const totalRefundAmount = refunds.reduce((sum, s) => sum + Math.abs(s.total || 0), 0);

  const cashTotal = regularSales.filter(s => s.payment_method === 'Cash').reduce((sum, s) => sum + s.total, 0);
  const cardTotal = todaySales.filter(s => s.payment_method === 'Card').reduce((sum, s) => sum + s.total, 0);
  const mobileTotal = todaySales.filter(s => s.payment_method === 'Mobile Transfer').reduce((sum, s) => sum + s.total, 0);

  const handlePrintZReport = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Z-Report - ${today}</title>
          <style>
            body { font-family: monospace; font-size: 12px; padding: 10px; width: 240px; margin: 0 auto; color: #000; }
            .header { text-align: center; font-weight: bold; font-size: 16px; margin-bottom: 4px; }
            .line { border-bottom: 1px dashed #000; margin: 6px 0; }
            .row { display: flex; justify-content: space-between; margin: 3px 0; }
            .bold { font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="header">${settings.store_name || 'BRUSHWELL BOOKS'}</div>
          <div style="text-align:center;">END-OF-DAY Z-REPORT</div>
          <div class="line"></div>
          <div>Date: ${new Date().toLocaleDateString()}</div>
          <div>Time: ${new Date().toLocaleTimeString()}</div>
          <div>Generated By: ${session?.name || 'Admin'}</div>
          <div class="line"></div>
          <div class="row"><span>Total Orders:</span><span class="bold">${regularSales.length}</span></div>
          <div class="row"><span>Total Items Sold:</span><span class="bold">${regularSales.reduce((sum, s) => sum + s.items.reduce((a, i) => a + i.quantity, 0), 0)}</span></div>
          <div class="line"></div>
          <div class="row"><span>Gross Subtotal:</span><span>GH₵${totalSubtotal.toFixed(2)}</span></div>
          <div class="row"><span>Tax/VAT Collected:</span><span>+GH₵${totalTax.toFixed(2)}</span></div>
          <div class="row"><span>Refunds Processed:</span><span>-GH₵${totalRefundAmount.toFixed(2)}</span></div>
          <div class="line"></div>
          <div class="row bold" style="font-size:14px;"><span>NET TOTAL REVENUE:</span><span>GH₵${totalRevenue.toFixed(2)}</span></div>
          <div class="line"></div>
          <div class="bold">TILL BALANCING SUMMARY</div>
          <div class="row"><span>Cash Total:</span><span>GH₵${cashTotal.toFixed(2)}</span></div>
          <div class="row"><span>Card Total:</span><span>GH₵${cardTotal.toFixed(2)}</span></div>
          <div class="row"><span>Mobile Transfer:</span><span>GH₵${mobileTotal.toFixed(2)}</span></div>
          <div class="line"></div>
          <div style="text-align:center; font-size:10px; margin-top:8px;">
            End of Shift Till Audit<br/>Brushwell Books System
          </div>
          <script>
            setTimeout(() => { window.print(); window.close(); }, 400);
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={e => e.stopPropagation()} style={{ maxWidth: '420px' }}>
        
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <FileText size={20} color="var(--primary)" />
            <div>
              <h3 style={{ fontSize: '1.05rem', fontWeight: 700 }}>End-of-Day Z-Report</h3>
              <div style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>Daily Till Audit & Revenue Closing</div>
            </div>
          </div>
          <button className="btn-icon" onClick={onClose}><X size={18} /></button>
        </div>

        <div className="modal-body">
          <div style={{
            background: '#ffffff',
            color: '#000',
            fontFamily: "'Courier New', Courier, monospace",
            fontSize: '12px',
            padding: '1rem',
            borderRadius: 'var(--radius-md)',
            boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
            border: '1px solid #ddd',
            marginBottom: '1rem'
          }}>
            <div style={{ textAlign: 'center', fontWeight: 'bold', fontSize: '15px', marginBottom: '2px' }}>
              {settings.store_name || 'BRUSHWELL BOOKS'}
            </div>
            <div style={{ textAlign: 'center', fontSize: '11px', marginBottom: '6px' }}>
              DAILY CLOSING Z-REPORT
            </div>
            <div style={{ borderBottom: '1px dashed #999', marginBottom: '6px' }}></div>

            <div>Date: {new Date().toLocaleDateString()}</div>
            <div>Time: {new Date().toLocaleTimeString()}</div>
            <div>Audit By: <strong>{session?.name || 'Admin'}</strong></div>

            <div style={{ borderBottom: '1px dashed #999', margin: '6px 0' }}></div>

            <div style={{ display: 'flex', justifyContent: 'space-between', margin: '2px 0' }}>
              <span>Total Orders:</span>
              <strong>{regularSales.length}</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', margin: '2px 0' }}>
              <span>Subtotal:</span>
              <span>GH₵{totalSubtotal.toFixed(2)}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', margin: '2px 0' }}>
              <span>Tax / VAT Collected:</span>
              <span>+GH₵{totalTax.toFixed(2)}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', margin: '2px 0' }}>
              <span>Refunds Issued:</span>
              <span>-GH₵{totalRefundAmount.toFixed(2)}</span>
            </div>

            <div style={{ borderBottom: '1px dashed #999', margin: '6px 0' }}></div>

            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '14px', fontWeight: 'bold' }}>
              <span>NET REVENUE:</span>
              <span>GH₵{totalRevenue.toFixed(2)}</span>
            </div>

            <div style={{ borderBottom: '1px dashed #999', margin: '6px 0' }}></div>

            <div style={{ fontWeight: 'bold', marginBottom: '4px' }}>TILL RECONCILIATION</div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>💵 Cash in Till:</span>
              <span>GH₵{cashTotal.toFixed(2)}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>💳 Card Payments:</span>
              <span>GH₵{cardTotal.toFixed(2)}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span>📱 Mobile Transfer:</span>
              <span>GH₵{mobileTotal.toFixed(2)}</span>
            </div>
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn-secondary" onClick={onClose}>Close</button>
          <button className="btn-primary" onClick={handlePrintZReport} style={{ flex: 1 }}>
            <Printer size={16} />
            Print Z-Report
          </button>
        </div>

      </div>
    </div>
  );
}
